ndmin制定数组的最小维度

In [206]:
# ndmin最小维度设置成2
import numpy as np
a = np.array([1,2,3],ndmin=2)
a

array([[1, 2, 3]])

In [207]:
dt = np.dtype(np.int32)
dt

dtype('int32')

int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替

In [208]:
dt = np.dtype('i8')
dt

dtype('int64')

In [209]:
dt = np.dtype([('age',np.int8)])
dt

dtype([('age', 'i1')])

In [210]:
a = np.arange(24)
print(a.ndim)
a = a.reshape(2,3,4)
print(a.ndim)
a.shape=(4,6)
print(a.ndim)

1
3
2


创建数组

1、empty： 数组元素为随机值，因为它们未初始化

2、zeros：创建指定大小的数组，数组元素以 0 来填充

3、ones：创建指定形状的数组，数组元素以 1 来填充

In [6]:
a = np.empty((2,3))
a

array([[1.117e-321, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [7]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

从已有的数组创建数组  asarray   frombuffer: 用于实现动态数组    fromiter

In [9]:
a = np.asarray([(1,2,3),(4,5,6)],dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
s = b'hello world'
a = np.frombuffer(s,dtype='S1')
a

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],
      dtype='|S1')

In [11]:
a = np.fromiter(iter(range(6)),dtype=float)
a

array([0., 1., 2., 3., 4., 5.])

从数值范围创建数组

In [12]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [13]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的

In [14]:
a = np.linspace(1,10,2)
a

array([ 1., 10.])

In [15]:
a = np.linspace(1,1,2)
a

array([1., 1.])

创建等差数列

In [16]:
a = np.linspace(10, 20,  5, endpoint =  False,retstep= True)  
print(a)

(array([10., 12., 14., 16., 18.]), 2.0)


In [17]:
a = np.linspace(10, 20,  5, endpoint =  True,retstep= True)  
print(a)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)


创建等比数列

In [18]:
a = np.logspace(0,9,10,base=2)#base=2:等比的比是2
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

切片

In [19]:
a = np.arange(10)
b = a[slice(1,6,2)]
print(a)
b

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5])

In [20]:
print(a)
b = a[0:10:2]
b

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

In [21]:
print(b)
print(b[3])
print(b[3:])
print(b[3:4])

[0 2 4 6 8]
6
[6 8]
[6]


In [22]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [23]:
print(a[:,1])

[2 4 5]


In [24]:
print(a[1,...])

[3 4 5]


In [25]:
print(a[1,1:3])

[4 5]


NumPy 高级索引

In [26]:
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
y = x[[0],[0]]
print(y)

[1]


取（0,0），（1,0），（2,1）的元素

In [28]:
y = x[[0,1,2],[0,0,1]]
print(y)

[1 3 6]


In [29]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print(x)
print('*'*20)
rows = np.array([[0,0],[3,3]]) 
cols = np.array([[0,2],[0,2]]) 
print(rows)
print('*'*20)
print(cols)
print('*'*20)
y = x[rows,cols]
print(y)
print('*'*20)
y = x[[[0,0],[3,3]],[[0,2],[0,2]]]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
********************
[[0 0]
 [3 3]]
********************
[[0 2]
 [0 2]]
********************
[[ 0  2]
 [ 9 11]]
********************
[[ 0  2]
 [ 9 11]]


In [30]:
x = np.arange(12).reshape(4,3)
print(x)
print(x[x>5])
print(x>5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]


过滤数组例子

In [31]:
a = np.array([1,  2+6j,  5,  3.5+5j])  
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [32]:
x = np.arange(32).reshape(8,4)
print(x)
print('*'*20)
print(x[[4,2,1,7]])
print('*'*20)
print(x[[-4,-2,-1,-7]])#-1是最后一个

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
********************
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
********************
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [33]:
x = np.arange(32).reshape(8,4)
print(x)
print('*'*20)
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
********************
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


广播

数组形状相同的a，b运算

In [34]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)

[ 10  40  90 160]


数组形状不相同的a，b运算，numpy自动触发广播机制

In [35]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a)
print('*'*20)
print(b)
print('*'*20)
print(a+b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
********************
[1 2 3]
********************
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [36]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a)
print('*'*20)
print(b)
bb = np.tile(b, (4, 1))
print('*'*20)
print(bb)
print('*'*20)
print(a+bb)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
********************
[1 2 3]
********************
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
********************
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


迭代数组

In [37]:
a = np.arange(6).reshape(2,3)
print(a)
print('********************')
for n in np.nditer(a):
    print(n,end=' ')
print()
for n in np.nditer(a.T):
    print(n,end=' ')
print()
for n in np.nditer(a.T.copy(order='C')):
    print(n,end=' ')

[[0 1 2]
 [3 4 5]]
********************
0 1 2 3 4 5 
0 1 2 3 4 5 
0 3 1 4 2 5 

控制遍历顺序
for x in np.nditer(a, order='F'):Fortran order，即是列序优先；
for x in np.nditer(a.T, order='C'):C order，即是行序优先；

In [38]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('*'*20)
b = a.T
print(b)
print('*'*20)
print(b.copy(order='C'))
for n in np.nditer(b.copy(order='C')):
    print(n,end=' ')
print()
print('*'*20)
print(b.copy(order='F'))
for n in np.nditer(b.copy(order='F')):
    print(n,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
********************
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
********************
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 20 40 5 25 45 10 30 50 15 35 55 
********************
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

可以通过显式设置，来强制 nditer 对象使用某种顺序

In [39]:
print(a)
print('*'*20)
for x in np.nditer(a,order='C'):
    print(x,end=' ')
print()
print('*'*20)
for x in np.nditer(a,order='F'):
    print(x,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
********************
0 5 10 15 20 25 30 35 40 45 50 55 
********************
0 20 40 5 25 45 10 30 50 15 35 55 

In [40]:
print(a)
print('*'*20)
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = 2*x
print(a)
print('*'*20)
print(a*2)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
********************
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
********************
[[  0  20  40  60]
 [ 80 100 120 140]
 [160 180 200 220]]


nditer类的构造器拥有flags参数，它可以接受下列值：

参数	描述

c_index	可以跟踪 C 顺序的索引

f_index	可以跟踪 Fortran 顺序的索引

multi-index	每次迭代可以跟踪一种索引类型

external_loop	给出的值是具有多个值的一维数组，而不是零维数组

In [41]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print('*'*20)
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x,end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
********************
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 

In [42]:
a = np.arange(0,60,5).reshape(3,4)
print(a)
print()
b = np.array([1,2,3,4])
print(b)
print()
for x,y in np.nditer([a,b]):
    print('%d:%d' % (x,y),end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

[1 2 3 4]

0:1 5:2 10:3 15:4 20:1 25:2 30:3 35:4 40:1 45:2 50:3 55:4 

数组元素迭代器

In [43]:
a = np.arange(9).reshape(3,3)
print(a)
print()
for n in a.flat:
    print(n,end=' ')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2 3 4 5 6 7 8 

numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

In [44]:
print(a)
print()
print(a.flatten())
print()
print(a.flatten(order='F'))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]

[0 3 6 1 4 7 2 5 8]


numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图，修改会影响原始数组。

order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

In [45]:
a = np.arange(8).reshape(2,4)
print(a)
print()
print(a.ravel())
print()
print(a.ravel(order='F'))
print()

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5 6 7]

[0 4 1 5 2 6 3 7]



numpy.rollaxis 函数向后滚动特定的轴到一个特定位置

In [46]:
a = np.arange(8).reshape(2,2,2)
print(a)
print('----------------')
print(np.rollaxis(a,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
----------------
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


numpy.swapaxes 函数用于交换数组的两个轴

In [47]:
print(a)
print('----------------')
print(np.swapaxes(a,2,0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
----------------
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [48]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6]) 
b = np.broadcast(x,y)
print(b)
print()
r,c = b.iters
print(next(r),next(c))
print(next(r),next(c))
print(next(r),next(c))
print()
print(b.shape)
b = np.broadcast(x,y)
c = np.empty(b.shape)
print(c.shape)
print()
c.flat = [u+v for (u,v) in b]
print(c)
print()
print(x+y)


1 4
1 5
1 6

(3, 3)
(3, 3)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]

[[5 6 7]
 [6 7 8]
 [7 8 9]]


numpy.broadcast_to 函数将数组广播到新形状。它在原始数组上返回只读视图。

In [49]:
a = np.arange(4).reshape(1,4)
print(a)
print()
print(np.broadcast_to(a,(4,4)))

[[0 1 2 3]]

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


numpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状

In [50]:
x = np.array(([1,2],[3,4]))
print(x)
print()
y = np.expand_dims(x,axis=0)
print(y)
print()
print(x.shape,y.shape)
print()
y = np.expand_dims(x,axis=1)
print(y)
print()
print(x.shape,y.shape)
print(x.ndim,y.ndim)

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]]

(2, 2) (1, 2, 2)

[[[1 2]]

 [[3 4]]]

(2, 2) (2, 1, 2)
2 3


numpy.squeeze 函数从给定数组的形状中删除一维的条目

In [51]:
a = np.arange(9).reshape(1,3,3)
print(a)
y = np.squeeze(a)
print(y)
print(a.shape,y.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(1, 3, 3) (3, 3)


In [52]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.vstack((a,b)))
print()
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [53]:
a = np.array([[1,2],[3,4]])
print(a)
print(np.vsplit(a,2))
print()
print(np.hsplit(a,2))

[[1 2]
 [3 4]]
[array([[1, 2]]), array([[3, 4]])]

[array([[1],
       [3]]), array([[2],
       [4]])]


numpy.resize 函数返回指定大小的新数组。

如果新数组大小大于原始大小，则包含原始数组中的元素的副本。有些情况用reshape会报错

In [54]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(a.shape)
print()
b = np.resize(a,(3,2))
print(b)
print()
print(b.shape)
print()
print(np.resize(a,(3,3)))
# print(a.reshape(3,3))

[[1 2 3]
 [4 5 6]]

(2, 3)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。 此外，输入数组的维度必须匹配否则将生成ValueError。

append 函数返回的始终是一个一维数组。

In [55]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(np.append(a,[7,8,9]))
print()
print(np.append(a,[[7,8,9]],axis=0))
print()
print(np.append(a,[[5,5,5],[7,8,9]],axis=1))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


numpy.insert 函数在给定索引之前，沿给定轴在输入数组中插入值。

如果值的类型转换为要插入，则它与输入数组不同。 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开

In [56]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()
print(np.insert(a,2,[7,8]))#未提供轴

[[1 2]
 [3 4]
 [5 6]]

[1 2 7 8 3 4 5 6]


In [57]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()
print(np.insert(a,2,[7,8],axis=0))#提供0轴

[[1 2]
 [3 4]
 [5 6]]

[[1 2]
 [3 4]
 [7 8]
 [5 6]]


numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，如果未提供轴参数，则输入数组将展开。

In [58]:
a = np.arange(12).reshape(3,4)
print(a)
print()
print(np.delete(a,5))#未指定轴

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3  4  6  7  8  9 10 11]


In [59]:
a = np.arange(12).reshape(3,4)
print(a)
print()
print(np.delete(a,1,axis=1))#指定1轴

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


numpy.unique 函数用于去除数组中的重复元素。

In [60]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(np.unique(a))
u,indices = np.unique(a,return_inverse=True)
print(indices)
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]
返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


位运算

In [61]:
a,b = 13,17
print('二进制为')
print(bin(a))
print(bin(b))
print(np.bitwise_and(a,b))
print(bin(np.bitwise_or(a,b)))
print(bin(np.invert(a)))

二进制为
0b1101
0b10001
1
0b11101
-0b1110


In [62]:
print(np.binary_repr(10))
a = np.left_shift(10,2)
print(a)
print(np.binary_repr(a))
print()
a = np.right_shift(10,2)
print(a)
print(np.binary_repr(a,width=8))

1010
40
101000

2
00000010


字符串

In [63]:
print(np.char.add(['hello'],['xyz']))

['helloxyz']


In [64]:
print(np.char.add(['hello','hi'],['abc','xyz']))

['helloabc' 'hixyz']


In [65]:
print(np.char.multiply('abc ',2))

abc abc 


In [66]:
print(np.char.center('QAQ',20,fillchar='-'))

--------QAQ---------


In [67]:
print(np.char.capitalize('abc'))

Abc


In [68]:
print(np.char.title('as df fff df'))

As Df Fff Df


In [69]:
print(np.char.lower('ASDFFFF'))

asdffff


In [70]:
print(np.char.upper('dfsfsd'))

DFSFSD


In [71]:
print(np.char.split('wwww.w.w.ere.rer',sep='.'))#默认分割符是空格

['wwww', 'w', 'w', 'ere', 'rer']


In [72]:
print(np.char.splitlines('''dsfsdf\nsdds\ndfs'''))

['dsfsdf', 'sdds', 'dfs']


In [73]:
print(np.char.strip('ssd dsfdsaas','s'))
print(np.char.strip(['ssds','sdsfdsaass'],'s'))

d dsfdsaa
['d' 'dsfdsaa']


In [74]:
print(np.char.join(':','abcdefg'))

a:b:c:d:e:f:g


In [75]:
print(np.char.replace('aa ddaa aaddd','aa','AA'))

AA ddAA AAddd


In [76]:
a = np.char.encode('wwwweee','cp500')
print(a)
print(np.char.decode(a,'cp500'))

b'\xa6\xa6\xa6\xa6\x85\x85\x85'
wwwweee


In [77]:
a = np.array([0,30,45,60,90])
print(np.sin(a*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]


numpy.floor() 返回小于或者等于指定表达式的最大整数，即向下取整。

In [78]:
a = np.array([-1.7,1.5,-0.2,0.6,10])
print(a)
print(np.floor(a))

[-1.7  1.5 -0.2  0.6 10. ]
[-2.  1. -1.  0. 10.]


numpy.ceil() 返回大于或者等于指定表达式的最小整数，即向上取整。

In [79]:
a = np.array([-1.7,1.5,-0.2,0.6,10])
print(a)
print(np.ceil(a))

[-1.7  1.5 -0.2  0.6 10. ]
[-1.  2. -0.  1. 10.]


算数函数

In [80]:
a = np.arange(9,dtype=np.float_).reshape(3,3)
print(a)
b = np.array([10,10,10])
print('---------------------')
print(b)
print('---------------------')
print(np.add(a,b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
---------------------
[10 10 10]
---------------------
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [81]:
print(np.subtract(b,a))

[[10.  9.  8.]
 [ 7.  6.  5.]
 [ 4.  3.  2.]]


In [82]:
print(np.multiply(a,b))

[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [83]:
print(np.divide(a,b))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [84]:
a = np.array([0.25,  1.33,  1,  100])  
print(a)
print(np.reciprocal(a))

[  0.25   1.33   1.   100.  ]
[4.        0.7518797 1.        0.01     ]


In [85]:
a = np.array([10,10,10])
print(a)
print(np.power(a,2))
b = np.array([1,2,3])
print(np.power(a,b))

[10 10 10]
[100 100 100]
[  10  100 1000]


In [86]:
a = np.array([10,20,30])
a = np.array([3,5,7])
print(a)
print('--------------')
print(b)
print('--------------')
print(np.mod(a,b))
print('--------------')
print(np.remainder(a,b))

[3 5 7]
--------------
[1 2 3]
--------------
[0 1 1]
--------------
[0 1 1]


In [87]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)
print('---------------')
print(np.amin(a,1))
print('---------------')
print(np.amin(a,0))
print('---------------')
print(np.amax(a,0))
print('---------------')
print(np.amax(a,axis=0))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
---------------
[3 3 2]
---------------
[2 4 3]
---------------
[8 7 9]
---------------
[8 7 9]


numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。

In [88]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)
print(np.ptp(a))
print()
print(np.ptp(a,axis=0))
print()
print(np.ptp(a,axis=1))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
7

[6 3 6]

[4 5 7]


In [89]:
a = np.array([[30,65,70],[80,95,10],[50,90,60]])  
print ('我们的数组是：')
print (a)
print ('\n')
print(np.median(a))
print ('\n')
print(np.median(a,axis=0))
print ('\n')
print(np.median(a,axis=1))

我们的数组是：
[[30 65 70]
 [80 95 10]
 [50 90 60]]


65.0


[50. 90. 60.]


[65. 80. 60.]


In [90]:
print(np.mean(a))
print ('\n')
print(np.mean(a,axis=0))
print ('\n')
print(np.mean(a,axis=1))

61.111111111111114


[53.33333333 83.33333333 46.66666667]


[55.         61.66666667 66.66666667]


numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。

In [91]:
a = np.array([1,2,3,4])
print(a)
print()
print(np.average(a))

wet = np.array([4,3,2,1])
print(np.average(a,weights = wet))

[1 2 3 4]

2.5
2.0


标准差

In [92]:
print(np.std([1,2,3,4]))

1.118033988749895


方差

In [93]:
print(np.var([1,2,3,4]))

1.25


In [94]:
a = np.array([[3,7],[9,1]])
print(a)
print()
print(np.sort(a))
print()
print(np.sort(a,axis = 0))
print()
print(np.sort(a,axis = 1))

[[3 7]
 [9 1]]

[[3 7]
 [1 9]]

[[3 1]
 [9 7]]

[[3 7]
 [1 9]]


In [95]:
dt = np.dtype([('name','S10'),('age',int)])
a = np.array([('raju',21),('anil',25),('ravi',17),('amar',27)],dtype=dt)
print(a)
print()
print(np.sort(a,order='name'))
print()
print(np.sort(a,order='age'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]

[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]

[(b'ravi', 17) (b'raju', 21) (b'anil', 25) (b'amar', 27)]


In [96]:
a = np.array([3,1,2])
print(a)
print()
y = np.argsort(a)
print(y)
print(a[y])
for i in y:
    print(a[i])

[3 1 2]

[1 2 0]
[1 2 3]
1
2
3


numpy.lexsort() 用于对多个序列进行排序。把它想象成对电子表格进行排序，每一列代表一个序列，排序时优先照顾靠后的列。

In [102]:
nm =  ('raju','anil','ravi','amar') 
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.') 
ind1 = np.lexsort((dv,nm))
print(ind1)
print()
ind2 = np.lexsort((nm,dv))
print(ind2)

[3 1 0 2]

[3 0 1 2]


In [103]:
print(np.sort_complex([5,7,4,6,3,1]))

[1.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


In [104]:
 np.sort_complex([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j])

array([1.+2.j, 2.-1.j, 3.-3.j, 3.-2.j, 3.+5.j])

partition() 分区排序：

In [107]:
a = np.array([3,4,2,1])
print(np.partition(a,3))
print(np.partition(a,(1,3)))

[2 1 3 4]
[1 2 3 4]


In [121]:
arr = np.array([46, 57, 23, 39, 1, 10, 0, 120])
print(np.argpartition(arr,len(arr)-1))
print(arr[np.argpartition(arr,len(arr)-1)])#排好最大值
print()
print(np.argpartition(arr,0))
print(arr[np.argpartition(arr,0)])#排好最小值
print()
print(np.argpartition(arr,[2,3]))
print(arr[np.argpartition(arr,[2,3])])#排好第三第四个
print(arr[np.argpartition(arr,[2,3])][2])#打印第三大的元素
print()
print(arr)

[5 3 2 6 4 0 1 7]
[ 10  39  23   0   1  46  57 120]

[6 1 2 3 4 5 0 7]
[  0  57  23  39   1  10  46 120]

[6 4 5 2 1 3 0 7]
[  0   1  10  23  57  39  46 120]
10

[ 46  57  23  39   1  10   0 120]


numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。

In [122]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])  
print(a)
print()
print(a.flatten())
print(np.argmax(a))
print()
print(np.argmax(a,axis=0))
print()
print(np.argmax(a,axis=1))

[[30 40 70]
 [80 20 10]
 [50 90 60]]

[30 40 70 80 20 10 50 90 60]
7

[1 2 0]

[2 0 1]


numpy.nonzero() 函数返回输入数组中非零元素的索引。

In [123]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
print(a)
print(np.nonzero(a))#返回行索引数组和列索引数组

[[30 40  0]
 [ 0 20 10]
 [50  0 60]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


numpy.where() 函数返回输入数组中满足给定条件的元素的索引。

In [124]:
x = np.arange(9.).reshape(3,3)
print(x)
print()
y = np.where(x>3)
print(y)
print()
print(x[y])

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

[4. 5. 6. 7. 8.]


numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。

In [127]:
x = np.arange(9.).reshape(3,3)
print(x)
print()
condition = np.mod(x,2) == 0
print(np.extract(condition,x))
print()
condition = x>5
print(np.extract(condition,x))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

[0. 2. 4. 6. 8.]

[6. 7. 8.]


视图一般发生在：

1、numpy 的切片操作返回原数据的视图。

2、调用 ndarray 的 view() 函数产生一个视图。

副本一般发生在：

Python 序列的切片操作，调用deepCopy()函数。

调用 ndarray 的 copy() 函数产生一个副本。

In [134]:
a = np.arange(9)
b = a
print(a)
print(b)
print()
print(id(a),id(b))
print()
a.shape=3,3#一个数组的任何变化都反映在另一个数组上
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]

96356032 96356032

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


ndarray.view() 方会创建一个新的数组对象，该方法创建的新数组的维数更改不会更改原始数据的维数。

In [135]:
a = np.arange(6).reshape(3,2)
print(a)
print()
b = a.view()
print(id(a),id(b))
b.shape=2,3
print(b,'\n')
print(a)

[[0 1]
 [2 3]
 [4 5]]

96356112 96356192
[[0 1 2]
 [3 4 5]] 

[[0 1]
 [2 3]
 [4 5]]


使用切片创建视图修改数据会影响到原始数组：

In [139]:
arr = np.arange(12)
print(arr,'\n')
a = arr[3:]
b = arr[3:]
a[1] = 123
b[2] = 234
print(arr,'\n')
print(id(arr),id(a),id(b))#a,b 的 id，他们是不同的，也就是说，视图虽然指向原数据，但是他们和赋值引用还是有区别的

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[  0   1   2   3 123 234   6   7   8   9  10  11] 

96356912 96355392 96356032


ndarray.copy() 函数创建一个副本。 对副本数据进行修改，不会影响到原始数据，它们物理内存不在同一位置。

In [140]:
a = np.array([[10,10],[2,3],[4,5]])
print(a,'\n')
b = a.copy()
print(b,'\n')
print(b is a)
b[0,0] = 100
print(a,'\n')
print(b,'\n')

[[10 10]
 [ 2  3]
 [ 4  5]] 

[[10 10]
 [ 2  3]
 [ 4  5]] 

False
[[10 10]
 [ 2  3]
 [ 4  5]] 

[[100  10]
 [  2   3]
 [  4   5]] 



NumPy 矩阵库(Matrix)

In [144]:
import numpy.matlib
print(np.matlib.empty((2,2)))

[[1.20953760e-312 8.27578359e-313]
 [2.12199579e-313 2.54639495e-312]]


In [145]:
print(np.matlib.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [146]:
print(np.matlib.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [153]:
print(np.matlib.eye(5,8,0,int))

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]]


numpy.matlib.identity() 函数返回给定大小的单位矩阵。

In [155]:
print(np.matlib.identity(5,int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


numpy.matlib.rand() 函数创建一个给定大小的矩阵，数据是随机填充的。

In [157]:
print(np.matlib.rand(4,6))

[[0.26807764 0.37356956 0.41307383 0.02668281 0.9670862  0.46099585]
 [0.32368469 0.07681744 0.26268228 0.20896912 0.72959072 0.24462283]
 [0.85308001 0.56491486 0.92626894 0.67277787 0.47463177 0.58892313]
 [0.08597865 0.65507874 0.27510505 0.29970882 0.99242014 0.10034579]]


In [163]:
i = np.matrix('1,2;3,4')
print(i)
j = np.asarray(i)
print('\n',j)
k = np.asmatrix(j)
print('\n',k)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]]

 [[1 2]
 [3 4]]


dot矩阵乘法

In [166]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))

[[37 40]
 [85 92]]


In [168]:
print(a.flatten())
print(b.flatten())
print(np.vdot(a,b))

[1 2 3 4]
[11 12 13 14]
130


In [169]:
print (np.inner(np.array([1,2,3]),np.array([0,1,0])))

2


In [170]:
print(np.inner(a,b))

[[35 41]
 [81 95]]


In [171]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


In [172]:
a = [[1,0],[0,1]] 
b = [1,2] 
print (np.matmul(a,b))
print (np.matmul(b,a))

[1 2]
[1 2]


In [174]:
a = np.arange(8).reshape(2,2,2) 
print(a)
print(b)
b = np.arange(4).reshape(2,2) 
print (np.matmul(a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1]
 [2 3]]
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]


In [180]:
a = np.array([[1,2], [3,4]]) 
print (int(np.linalg.det(a)))

-2


In [182]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(b,'\n')
print(np.linalg.det(b))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]] 

-306.0


In [183]:
a = np.array([1,2,3,4,5])
np.save('testpandasdata/outfile.npy',a)#直接看会乱码，用load加载之后看就可以了

In [185]:
b = np.load('testpandasdata/outfile.npy')
print(b)

[1 2 3 4 5]


In [192]:
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(0, 1.0, 0.1)
c = np.sin(b)
np.savez('testpandasdata/runoob',a,b1=b,c1 = c)#非关键字参数传递的数组会自动起名为 arr_0, arr_1, …
r = np.load('testpandasdata/runoob.npz')
print(r['arr_0'])#非关键字参数传递的数组会自动起名为 arr_0, arr_1, …
print(r['b1'])

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [196]:
a = np.arange(6).reshape(2,-1)  #一个参数为-1时，那么reshape函数会根据另一个参数的维度计算出数组的另外一个shape属性值。
np.savetxt('testpandasdata/out.txt',a,delimiter=',')
b = np.loadtxt('testpandasdata/out.txt',delimiter=',')
print(b)

[[0. 1. 2.]
 [3. 4. 5.]]
